// Constantes de Mapeamento do Portal de Membros por Função Administrativa
export const DEFAULT_PORTAL_PERMISSIONS: Record<string, string[]> = {
    'NENHUMA': ['portal_home', 'portal_mural', 'portal_informativo', 'portal_biblia', 'portal_agenda', 'portal_candidato', 'portal_frequencia', 'portal_carteirinha'],
    'PASTOR PRESIDENTE': ['portal_home', 'portal_mural', 'portal_informativo', 'portal_biblia', 'portal_email', 'portal_agenda', 'portal_tarefas', 'portal_financas', 'portal_ebd', 'portal_cursos', 'portal_candidato', 'portal_frequencia', 'portal_salinha_kids', 'portal_carteirinha', 'portal_pastor'],
    'PASTOR AUXILIAR': ['portal_home', 'portal_mural', 'portal_informativo', 'portal_biblia', 'portal_email', 'portal_agenda', 'portal_tarefas', 'portal_financas', 'portal_ebd', 'portal_cursos', 'portal_candidato', 'portal_frequencia', 'portal_salinha_kids', 'portal_carteirinha', 'portal_pastor'],
    'COORDENADOR': ['portal_home', 'portal_mural', 'portal_informativo', 'portal_biblia', 'portal_email', 'portal_agenda', 'portal_tarefas', 'portal_cursos', 'portal_candidato', 'portal_frequencia', 'portal_salinha_kids', 'portal_carteirinha'],
    'SUPERINTENDENTE': ['portal_home', 'portal_mural', 'portal_informativo', 'portal_biblia', 'portal_email', 'portal_agenda', 'portal_ebd', 'portal_cursos', 'portal_candidato', 'portal_frequencia', 'portal_salinha_kids', 'portal_carteirinha'],
    'SECRETARIO': ['portal_home', 'portal_mural', 'portal_informativo', 'portal_biblia', 'portal_email', 'portal_agenda', 'portal_frequencia', 'portal_cursos', 'portal_candidato', 'portal_salinha_kids', 'portal_carteirinha'],
    'TESOUREIRO': ['portal_home', 'portal_mural', 'portal_informativo', 'portal_financas', 'portal_candidato', 'portal_salinha_kids', 'portal_carteirinha', 'portal_tesoureiro'],
    'CONTADOR': ['portal_home', 'portal_mural', 'portal_financas', 'portal_candidato', 'portal_carteirinha', 'portal_tesoureiro'],
    'ADMINISTRADOR': ['portal_home', 'portal_mural', 'portal_informativo', 'portal_email', 'portal_agenda', 'portal_tarefas', 'portal_financas', 'portal_ebd', 'portal_cursos', 'portal_candidato', 'portal_frequencia', 'portal_salinha_kids', 'portal_carteirinha', 'portal_pastor', 'portal_tesoureiro'],
    'ADVOGADO': ['portal_home', 'portal_mural', 'portal_informativo', 'portal_biblia', 'portal_candidato', 'portal_carteirinha'],
    'GERENTE': ['portal_home', 'portal_mural', 'portal_informativo', 'portal_email', 'portal_agenda', 'portal_tarefas', 'portal_financas', 'portal_candidato', 'portal_salinha_kids', 'portal_carteirinha'],
    'COMUNICACAO': ['portal_home', 'portal_mural', 'portal_informativo', 'portal_biblia', 'portal_email', 'portal_agenda', 'portal_tarefas', 'portal_cursos', 'portal_candidato', 'portal_salinha_kids', 'portal_carteirinha'],
    'DISCIPULADOR': ['portal_home', 'portal_mural', 'portal_informativo', 'portal_biblia', 'portal_email', 'portal_agenda', 'portal_tarefas', 'portal_cursos', 'portal_candidato', 'portal_frequencia', 'portal_salinha_kids', 'portal_carteirinha'],
    'LIDER_CELULA': ['portal_home', 'portal_mural', 'portal_informativo', 'portal_biblia', 'portal_agenda', 'portal_frequencia', 'portal_candidato', 'portal_carteirinha'],
    'LIDER': ['portal_home', 'portal_mural', 'portal_informativo', 'portal_biblia', 'portal_agenda', 'portal_frequencia', 'portal_candidato', 'portal_carteirinha'],
    'PROFESSOR': ['portal_home', 'portal_mural', 'portal_informativo', 'portal_biblia', 'portal_agenda', 'portal_ebd', 'portal_cursos', 'portal_frequencia', 'portal_candidato', 'portal_salinha_kids', 'portal_carteirinha'],
    'PROFESSOR_EBD': ['portal_home', 'portal_mural', 'portal_informativo', 'portal_biblia', 'portal_agenda', 'portal_ebd', 'portal_cursos', 'portal_frequencia', 'portal_candidato', 'portal_salinha_kids', 'portal_carteirinha'],
    'MONITOR': ['portal_home', 'portal_mural', 'portal_informativo', 'portal_biblia', 'portal_agenda', 'portal_ebd', 'portal_frequencia', 'portal_candidato', 'portal_salinha_kids', 'portal_carteirinha'],
    'RECEPCAO': ['portal_home', 'portal_mural', 'portal_informativo', 'portal_biblia', 'portal_agenda', 'portal_candidato', 'portal_frequencia', 'portal_carteirinha'],
    'PORTARIA': ['portal_home', 'portal_mural', 'portal_informativo', 'portal_biblia', 'portal_agenda', 'portal_candidato', 'portal_frequencia', 'portal_carteirinha'],
    'SOM': ['portal_home', 'portal_mural', 'portal_informativo', 'portal_biblia', 'portal_agenda', 'portal_candidato', 'portal_carteirinha'],
    'MIDIA': ['portal_home', 'portal_mural', 'portal_informativo', 'portal_biblia', 'portal_agenda', 'portal_candidato', 'portal_carteirinha'],
    'LOUVOR': ['portal_home', 'portal_mural', 'portal_informativo', 'portal_biblia', 'portal_agenda', 'portal_candidato', 'portal_carteirinha'],
    'MUSICO': ['portal_home', 'portal_mural', 'portal_informativo', 'portal_biblia', 'portal_agenda', 'portal_candidato', 'portal_carteirinha'],
    'CANTO': ['portal_home', 'portal_mural', 'portal_informativo', 'portal_biblia', 'portal_agenda', 'portal_candidato', 'portal_carteirinha'],
    'INFANTIL': ['portal_home', 'portal_mural', 'portal_informativo', 'portal_biblia', 'portal_agenda', 'portal_salinha_kids', 'portal_candidato', 'portal_carteirinha'],
    'DIACONATO': ['portal_home', 'portal_mural', 'portal_informativo', 'portal_biblia', 'portal_agenda', 'portal_candidato', 'portal_carteirinha'],
    'ZELEADOR': ['portal_home', 'portal_mural', 'portal_informativo', 'portal_biblia', 'portal_agenda', 'portal_candidato', 'portal_carteirinha'],
    'LIMPEZA': ['portal_home', 'portal_mural', 'portal_informativo', 'portal_biblia', 'portal_agenda', 'portal_candidato', 'portal_carteirinha'],
    'COZINHA': ['portal_home', 'portal_mural', 'portal_informativo', 'portal_biblia', 'portal_agenda', 'portal_candidato', 'portal_carteirinha'],
    'MANUTENCAO': ['portal_home', 'portal_mural', 'portal_informativo', 'portal_biblia', 'portal_agenda', 'portal_candidato', 'portal_carteirinha'],
    'SEGURANCA': ['portal_home', 'portal_mural', 'portal_informativo', 'portal_biblia', 'portal_agenda', 'portal_candidato', 'portal_carteirinha'],
    'OBREIRO': ['portal_home', 'portal_mural', 'portal_informativo', 'portal_biblia', 'portal_agenda', 'portal_candidato', 'portal_carteirinha'],
    'EVANGELISTA': ['portal_home', 'portal_mural', 'portal_informativo', 'portal_biblia', 'portal_agenda', 'portal_cursos', 'portal_candidato', 'portal_frequencia', 'portal_carteirinha'],
    'MISSIONARIO': ['portal_home', 'portal_mural', 'portal_informativo', 'portal_biblia', 'portal_agenda', 'portal_cursos', 'portal_candidato', 'portal_frequencia', 'portal_carteirinha'],
    'PRESBITERO': ['portal_home', 'portal_mural', 'portal_informativo', 'portal_biblia', 'portal_agenda', 'portal_cursos', 'portal_candidato', 'portal_frequencia', 'portal_carteirinha'],
    'DIACONO': ['portal_home', 'portal_mural', 'portal_informativo', 'portal_biblia', 'portal_agenda', 'portal_candidato', 'portal_carteirinha'],
    'COOPERADOR': ['portal_home', 'portal_mural', 'portal_informativo', 'portal_biblia', 'portal_agenda', 'portal_candidato', 'portal_carteirinha'],
    'MEMBRO': ['portal_home', 'portal_mural', 'portal_informativo', 'portal_biblia', 'portal_agenda', 'portal_candidato', 'portal_carteirinha'],
    'VISITANTE': ['portal_home', 'portal_mural', 'portal_informativo', 'portal_biblia', 'portal_agenda', 'portal_carteirinha'],
    'CONGREGADO': ['portal_home', 'portal_mural', 'portal_informativo', 'portal_biblia', 'portal_agenda', 'portal_carteirinha'],
};
